export const LANGUAGES = {
    "en-US":{
        LOGIN_HEADER: "test",
        FRONT_PAGE_TITLE: "Team4 - Watch TV Shows Online, Watch Movies Online",
        FRONT_TITLE: "Unlimited movies, TV shows, and more.",
        FRONT_SUBTITLE: "Watch anywhere. Cancel anytime.",
        FRONT_BUTTON_LOGIN: "Sign In",
        FRONT_REGISTER: "Ready to watch? Enter your email to create or restart your membership.",
        FRONT_BUTTON_REGISTER: "Get Started",
        FRONT_INPUT_TEXT: "Email address",
        FRONT_EMAIL_VERIFY: "Please enter a valid email address",
        REGISTER_TITLE: "Create a password to start your membership",
        REGISTER_SUBTITLE_1: "Just a few more steps and you're done!",
        REGISTER_SUBTITLE_2: "We hate paperwork, too.",
        RESISTER_PASS_LABEL: "Add a password",
        BUTTON_SIGNIN_GOOGLE: "Sign In with Google",
    },
    "es-ES":{
        LOGIN_HEADER: "prueba",
        FRONT_PAGE_TITLE: "Team4 - Ve series online, ve películas online",
        FRONT_TITLE: "Películas y series ilimitadas y mucho más",
        FRONT_SUBTITLE: "Disfruta donde quieras. Cancela cuando quieras.",
        FRONT_BUTTON_LOGIN: "Iniciar sesión",
        FRONT_REGISTER: "¿Quieres ver Netflix ya? Ingresa tu email para crear una cuenta o reiniciar tu membresía de Netflix.",
        FRONT_BUTTON_REGISTER: "Comenzar",
        FRONT_INPUT_TEXT: "Email",
        FRONT_EMAIL_VERIFY: "Escribe una dirección de email válida.",
        REGISTER_TITLE: "Crea una contraseña para que comiences tu membresía ó iniciá sesión con Google",
        REGISTER_SUBTITLE_1: "¡Unos pasos más y listo!",
        REGISTER_SUBTITLE_2: "Tampoco nos gustan los trámites.",
        RESISTER_PASS_LABEL: "Ingrese una contraseña",
        BUTTON_SIGNIN_GOOGLE: "Iniciar con Google",
    }
}