export const LANGUAGES = {
    "en-US":{
        LOGIN_HEADER: "test",
        FRONT_PAGE_TITLE: "Team4 - Watch TV Shows Online, Watch Movies Online",
        FRONT_TITLE: "Unlimited movies, TV shows, and more.",
        FRONT_SUBTITLE: "Watch anywhere. Cancel anytime.",
        FRONT_BUTTON_LOGIN: "Sign In",
        FRONT_REGISTER: "Ready to watch? Enter your email to create or restart your membership.",
        FRONT_BUTTON_REGISTER: "Get Started",
        FRONT_INPUT_TEXT: "Email address",
        FRONT_EMAIL_VERIFY: "Please enter a valid email address",
        REGISTER_TITLE: "Create a password to start your membership",
        REGISTER_SUBTITLE_1: "Just a few more steps and you're done!",
        REGISTER_SUBTITLE_2: "We hate paperwork, too.",
        RESISTER_PASS_LABEL: "Add a password",
        BUTTON_SIGNIN_GOOGLE: "Sign In with Google",
        MOVIES: "Movies",
        TV_SHOWS: "TV Shows",
        FILM: 'Film',
        SERIES: 'Series',
        MY_LIST: 'My List',
        HOME: 'Home',
        PLAY: 'Play',
        MORE_INFO: "More Info",
        NEW_POPULAR: "New & Popular",
        SEARCH_PLACEHOLDER: "Titles, people, genres",
        MANAGE_PROFILES: "Manage Profiles",
        ADD_PROFILE: "Add Profile",
        ADD_PROFILE_TEXT: "Add a profile for another person watching Netflix.",
        EDIT_PROFILE: "Edit Profile",
        PROFILE_EXISTS: "Profile name already exists",
        SAVE: "Save",
        CANCEL: "Cancel",
        CONTINUE: "Continue",
        DELETE_PROFILE: "Delete Profile",
        DELETE_PROFILE_Q: "Delete Profile?",
        DELETE_TEXT: "This profile's history - including My List, ratings and activity - will be gone forever, and you won't be able to access it again.",
        KEEP_PROFILE: "Keep Profile",
        KID: "Kid?",
        KID_TOOLTIP: "Si se selecciona esta opción, este perfil solo puede ver películas y series clasificadas para menores de 12&nbsp;años.",
        DONE: "Done",
        LOGOUT: "Sign out of Netflix",
        GENRE: "Genre",
        RELEASE_DATE: "Release Date",
        AUDIO_DESCRIPTION: "Audio Description",        
        INVESTOR_RELATIONS: "Investor Relations",
        LEGAL_NOTICE: "Legal Notice",
        HELP_CENTER: 'Help Center',
        JOBS: 'Jobs',
        COOKIE_PREF: "Cookie Preferences",
        GIFT_CARDS: "Gift Cards",
        TERM_USE: "Term of Use",
        CORPORATE_INFO: "Corporate Information",
        MEDIA_CENTER: "Media Center",
        PRIVACY: "Privacy",
        CONTACT_US: "Contact Us",
        ADD_LIST: "Add to My List",
        REMOVE_LIST: "Remove from My List",
        HOME_PAGE: "Home",
        TRENDING_NOW: "Trending Now",
        NEW_RELEASES: "New Releases",
        ACTION_THRILLERS: "Action Thrillers",
        EPICS: "Epics",
        POPULAR: "Popular",
        WATCH_WEEKEND: "Watch In One Weekend",
        CAST: "Cast",
        THIS_SHOW_IS: "This show is",
        THIS_MOVIE_IS: "This movie is",
        MATCH: "Match",
        WHOS_WATCHING: "Who's watching?",
        NAME: "Name",
    },
    "es-ES":{
        LOGIN_HEADER: "prueba",
        FRONT_PAGE_TITLE: "Team4 - Ve series online, ve películas online",
        FRONT_TITLE: "Películas y series ilimitadas y mucho más",
        FRONT_SUBTITLE: "Disfruta donde quieras. Cancela cuando quieras.",
        FRONT_BUTTON_LOGIN: "Iniciar sesión",
        FRONT_REGISTER: "¿Quieres ver Netflix ya? Ingresa tu email para crear una cuenta o reiniciar tu membresía de Netflix.",
        FRONT_BUTTON_REGISTER: "Comenzar",
        FRONT_INPUT_TEXT: "Email",
        FRONT_EMAIL_VERIFY: "Escribe una dirección de email válida.",
        REGISTER_TITLE: "Crea una contraseña para que comiences tu membresía ó iniciá sesión con Google",
        REGISTER_SUBTITLE_1: "¡Unos pasos más y listo!",
        REGISTER_SUBTITLE_2: "Tampoco nos gustan los trámites.",
        RESISTER_PASS_LABEL: "Ingrese una contraseña",
        BUTTON_SIGNIN_GOOGLE: "Iniciar con Google",
        MOVIES: "Películas",
        TV_SHOWS: "Series",
        FILM: 'Plelícula',
        SERIES: 'Serie',
        MY_LIST: 'Mi lista',
        HOME: 'Inicio',
        PLAY: 'Reproducir',
        MORE_INFO: "Más Información",
        NEW_POPULAR: "Novedades populares",
        SEARCH_PLACEHOLDER: "Títulos, personas, géneros",
        MANAGE_PROFILES: "Administrar perfiles",        
        ADD_PROFILE: "Agregar perfil",
        ADD_PROFILE_TEXT: "Agrega un perfil para otra persona que ve Netflix.",
        EDIT_PROFILE: "Editar perfil",
        PROFILE_EXISTS: "Ya existe ese nombre de perfil",
        SAVE: "Guardar",
        CANCEL: "Cacnelar",
        CONTINUE: "Continuar",
        DELETE_PROFILE: "Eliminar perfil",
        DELETE_PROFILE_Q: "¿Eliminar perfil?",
        DELETE_TEXT: "El historial de este perfil, incluidas Mi lista, los votos y la actividad, se eliminará definitivamente, por lo que no tendrás acceso a ellos después.",
        KEEP_PROFILE: "Guardar perfil",
        KID: "¿Niños?",
        KID_TOOLTIP: "Si se selecciona esta opción, este perfil solo puede ver películas y series clasificadas para menores de 12 años.",
        DONE: "Listo",
        LOGOUT: "Cerrar sesión en Netflix",
        GENRE: "Género",
        RELEASE_DATE: "Fecha de estreno",
        AUDIO_DESCRIPTION: "Audio descriptivo",
        INVESTOR_RELATIONS: "Relaciones con inversionistas",
        LEGAL_NOTICE: "Avisos legales",
        HELP_CENTER: 'Centro de ayuda',
        JOBS: 'Empleo',
        COOKIE_PREF: "Preferencias de cookies",
        GIFT_CARDS: "Tarjetas de regalo",
        TERM_USE: "Términos de uso",
        CORPORATE_INFO: "Información corporativa",
        MEDIA_CENTER: "Prensa",
        PRIVACY: "Privacidad",
        CONTACT_US: "Contáctanos",
        ADD_LIST: "Agregar a Mi lista",
        REMOVE_LIST: "Borrar de Mi lista",
        HOME_PAGE: "Página de inicio",
        TRENDING_NOW: "Tendecias",
        NEW_RELEASES: "Nuevos lanzamientos",
        ACTION_THRILLERS: "Películas de acción",
        EPICS: "Épicas",
        POPULAR: "Popular",
        WATCH_WEEKEND: "Planes para el finde",
        CAST: "Elenco",
        THIS_SHOW_IS: "Este título es",
        THIS_MOVIE_IS: "Este título es",
        MATCH: "para tí",
        WHOS_WATCHING: "¿Quién está viendo ahora?",
        NAME: "Nombre",
    }
}